name: compare-helm-with-jsonnet

on: pull_request

jobs:
  compare-manifests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: helm/kind-action@v1.2.0
    - uses: frenck/action-setup-yq@a2ad11c46c5d7ba576861216963c9365b53f35bc
    - uses: dsaltares/fetch-gh-release-asset@d9376dacd30fd38f49238586cd2e9295a8307f4cmaster
      with:
        repo: 'grafana/tanka'
        version: 'tags/v0.22.1'
        file: 'tk-linux-amd64'
        target: 'bin/tk'
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        set -e
        chmod +x $PWD/bin/tk
        echo $PWD/bin >> $GITHUB_PATH
    - run: make check-helm-jsonnet-diff
